language: php

php:
- '7.2'
- '7.3'

env:
- LARAVEL=^6.0

sudo: false

install:
  - composer require "laravel/framework=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --verbose
